name: Build and Test React Application

on:
  pull_request:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: npm ci, build and test
        run: |
          npm ci
          npm run build
          npm test
